### ISSUE TITLE
GPU memory overload

### ISSUE THREAD

**Issue by 1304150468** [CVRP-SOLE/SOLE#3]
Due to limited GPU resources, my system experiences memory overload during training and testing. I would like to know if it's possible to reduce the number of Precomputed per-point CLIP features (.pt files) during training or testing, or if there are other effective methods to address this issue. If it's possible to reduce the number of files, where should I make the modifications in the code? I eagerly await your response!

**Comment by 0nandon** [comment]
Thanks for your interest. Unfortunately, training/testing to each scene requires to use its corresponding pre-computed CLIP features. For example, if you want to train/test model in scene0000_00, you need to use pointwise CLIP features of this scene. So if you are going to train/test the model in the whole training or validation dataset, you need to use CLIP features for all of these scenes.

Btw, can you let me know the GPU memory size you are using now?

**Comment by 1304150468** [comment]
Sorry for the late reply. Here is the display of my GPU memory.
![image](https://github.com/CVRP-SOLE/SOLE/assets/106361049/e46681c1-87c3-425b-b2fd-5ac75e7fd3ca)

**Comment by 1304150468** [comment]
What I understand is, if I only use a portion of the dataset for testing or training (i.e., by reducing the dataset, and accordingly only having the CLIP features for those specific scenes), the code can still perform the testing and training, right?

**Comment by 0nandon** [comment]
Since your GPU memory size is 24GB, testing can be available. However, you may need over 40GB GPU memory to train our SOLE model on ScanNet dataset. So, although you decrease the number of scenes, training may still be not available due to the memory limitation.

+ Even though you use 24GB GPU memory, testing process can be killed due to insufficient CPU memory. This is due to the inherent heavy memory requirement of Mask3D which is the baseline of our model. You may refer to this [link](https://github.com/JonasSchult/Mask3D/issues/107).

**Comment by 1304150468** [comment]
Alright, I will think of some other ways. Thank you.
