### ISSUE TITLE
Evaluate the Model in Out-Of-Distribution dataset

### ISSUE THREAD

**Issue by SergioArnaud** [CVRP-SOLE/SOLE#6]
Congrats on the nice work.

I setup the code and downloaded the trained weights. I would like to evaluate the models performance in out of distribution so effectivelly I would like to evaluate the model in one of my non-scannet scenes; What would be a good way to do so?

Thanks

**Comment by 0nandon** [comment]
Nice to meet you. In order to evaluate SOLE in another dataset, you should manually fix/add the following files:

1. `conf/data/datasets/{name_of_your_dataset.yaml}`
2. `datasets/semseg.py`
3. `datasets/utils.py`

Furthermore, since SOLE is following the Mask3D structure and they also provide the python script to load the dataset other than ScanNet, you may check their repository.
