### ISSUE TITLE
visualization of the results and Replica dataset

### ISSUE THREAD

**Issue by 1304150468** [CVRP-SOLE/SOLE#9]
Hello, I would like to know how to achieve the visualization of the results for scene instance segmentation. Additionally, I am very much looking forward to the release of the Replica dataset. Thank you for your contributions to this project

**Comment by 0nandon** [comment]
Hi @1304150468.

1. Since SOLE is based on the code of Mask3D, it supports visualization with `pyviz3d` library. You may refer to this [line](https://github.com/CVRP-SOLE/SOLE/blob/b0dec6109d3ca0e93b2fe486daaf88ae47ebdf93/trainer/opentrainer.py#L972) in `trainer\opentrainer.py`.

2. Since authors are currently occupied to other project and paper is under review, the code and weight for Replica dataset will be released after the paper is accepted. Thanks for your understanding and stay tuned!
